# Generated by Django 6.0.3 on 2026-03-20 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("sigla", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="position",
            name="department",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="position",
        ),
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("cargo", models.CharField(max_length=80)),
                ("salario", models.DecimalField(decimal_places=2, max_digits=12)),
                ("data_admissao", models.DateField()),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.departamento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ferias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ferias",
                        to="core.funcionario",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
        migrations.DeleteModel(
            name="Position",
        ),
    ]
