# Generated by Django 6.0.3 on 2026-04-07 04:03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_departamento_remove_position_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['nome'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='ferias',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Férias', 'verbose_name_plural': 'Férias'},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['nome'], 'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nome',
            field=models.CharField(help_text='Nome do departamento', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='sigla',
            field=models.CharField(help_text='Sigla do departamento (ex: RH, TI)', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='ferias',
            name='data_fim',
            field=models.DateField(help_text='Data de término das férias'),
        ),
        migrations.AlterField(
            model_name='ferias',
            name='data_inicio',
            field=models.DateField(help_text='Data de início das férias'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(help_text='CPF no formato XXX.XXX.XXX-XX', max_length=14, unique=True, validators=[core.models.validar_cpf]),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(help_text='Data de admissão', validators=[core.models.validar_data_admissao]),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='salario',
            field=models.DecimalField(decimal_places=2, help_text='Salário mensal em reais', max_digits=12, validators=[core.models.validar_salario]),
        ),
    ]
